nodeLinker: node-modules

npmRegistries:
  //npm.fontawesome.com/:
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
