// This file is generated by scripts/generate-content-manifest.mjs. Do not edit manually.
import type { Locale } from "@common/config";
import type { Category } from "@modules/category";
import type { ComponentType } from "react";
import type { StaticImageData } from "next/image";
import image_article_2025_12_live_editor from "./articles/2025-12/live-editor/assets/i1.jpg";

export type ContentEntry = {
  slug: string;
  locales: ReadonlyArray<Locale>;
  createdAt: string;
  updatedAt: string;
  category?: Category;
  tags?: string[];
  title: Record<Locale, string>;
  summary: Record<Locale, string>;
  imageAlt: Record<Locale, string>;
  image: StaticImageData;
  mdx: Record<Locale, () => Promise<{ default: ComponentType }>>;
};

const entry_article_2025_12_live_editor = {
  slug: "article/2025-12/live-editor",
  locales: ["ko", "en"] as const,
  createdAt: "2025-12-20",
  updatedAt: "2025-12-20",
  category: "기술" as Category,
  tags: [],
  title: {
    ko: "고객 사이트에서 동작하는 React + Tailwind 앱 효율적으로 개발하기 (Production-Ready)",
    en: "Efficiently Building a React + Tailwind App That Runs on Customer Sites (Production-Ready)",
  } as Record<Locale, string>,
  summary: {
    ko: "배너 삽입 시스템을 만들고 동작시키고 개발하면서 이렇게 특수한 환경에서의 프론트엔드 개발에 대해 알아봅니다.",
    en: "Build a banner injection system and learn how to develop front-end apps in this special environment.",
  } as Record<Locale, string>,
  imageAlt: {
    ko: "포스트잇 사진.",
    en: "Sticky note photo.",
  } as Record<Locale, string>,
  image: image_article_2025_12_live_editor,
  mdx: {
    ko: () => import("./articles/2025-12/live-editor/ko.mdx"),
    en: () => import("./articles/2025-12/live-editor/en.mdx"),
  },
} satisfies ContentEntry;

export const contentEntries: ContentEntry[] = [
  entry_article_2025_12_live_editor,
];

export const contentBySlug: Record<string, ContentEntry> = {
  [entry_article_2025_12_live_editor.slug]: entry_article_2025_12_live_editor,
};
