-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Enable update for super user"
    ON public.posts
    AS PERMISSIVE
    FOR UPDATE
    TO authenticated
    USING ((auth.email() = 'eszqsc112@gmail.com'::text))
    WITH CHECK ((auth.email() = 'eszqsc112@gmail.com'::text));


CREATE POLICY "Enable read access for all users only published"
    ON public.posts
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((published = true));

CREATE POLICY "Enable insert for super user"
    ON public.posts
    AS PERMISSIVE
    FOR INSERT
    TO authenticated
    WITH CHECK ((auth.email() = 'eszqsc112@gmail.com'::text));


DROP POLICY IF EXISTS "Enable read access for all users" ON public.posts;
