name: "Setup Node and install dependencies"
description: "Configure Node, enable pnpm cache, and install dependencies"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "24"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: package install
      run: pnpm install
      shell: bash
